project:
  type: book
  output-dir: docs

book:
  title: "ENGSCI 355 Labs"
  author: "Thomas Adams"
  date: "08/29/2024"
  chapters:
    - index.qmd
    - part: "Practical Lab"
      chapters:
        - chapters/hands_on_production/hands_on_production.qmd
    - part: "Conceptual Modelling Labs"
      chapters:
        - chapters/cm_entities_behaviour/cm_entities_behaviour.qmd
        - chapters/cm_events_activities/cm_events_activities.qmd
    - part: "Jaamsim Labs"
      chapters:
        - chapters/vscode_java_setup/vscode_java_setup.qmd
        - chapters/jaamsim_setup/jaamsim_setup.qmd
        - chapters/clinic_1/clinic_1.qmd
    #     - chapters/lab_2/lab_2.qmd
    - part: "Conceptual Models"
      chapters:
        - chapters/paper_car_cm/paper_car_cm.qmd
        - chapters/clinic_1_cm/clinic_1_cm.qmd
    # - summary.qmd
    # - references.qmd
  downloads: pdf

# bibliography: references.bib

pdf-engine: pdflatex

reference-location: margin
citation-location: margin
# tbl-cap-location: bottom
# fig-cap-location: margin

latex-auto-install: true

callout-icon: false

filters:
  - parse-latex
  - latex-environment

environments: [mdframed, codebox, codeout]

format:
  html:
    theme: lumen
    code-line-numbers: true
    syntax-definitions: 
      - cm_pseudo.xml
    highlight-style: haddock
    default-image-extension: svg
    css: styles.css
  pdf:
    documentclass: scrreprt
    papersize: a4paper
    fontsize: 10pt
    include-in-header: preamble.tex
    fig-pos: htbp
    tbl-pos: htbp
    geometry:
      # - showframe
      - top=25mm
      - bottom=25mm
      - left=17.5mm
      - right=82.5mm
      - marginparsep=10mm
      - marginparwidth=55mm
    code-line-numbers: true
    # code-block-border-left: true
    default-image-extension: pdf
    # keep-tex: true

crossref:
  custom:
    - kind: float
      reference-prefix: Control Policy
      key: cntrlplcy
      latex-env: cntrlplcy

# syntax-definitions: 
#   - pseudocode.xml

