# Data, Structure, and Logic

In this lab you will complete the remainder of the fourth phase of the HCCM framework, with your group.

## Define the Data

Firstly, you need to give detailed definitions of the data modules.
You may not have collected data during car making, but complete the following table that describes the kind of data you would need to collect to simulate car making.
Also add a comment on how the entry for CutTapeDuration would change if no person-by-person data was available, but an Exponential distribution that estimated the time it takes for a person to cut tape was available.

::: {.content-visible unless-profile="answers"}

::: {#tbl-data_pc .sm .column-page-right .borderless}

```{=latex}
{{< include tables/data_table.tex >}}
```

List of Data Modules

:::

:::

::: {.content-visible when-profile="answers"}

::: {#tbl-data_pc .sm .column-page-right .borderless}

```{=latex}
{{< include tables/data_table_ans.tex >}}
```

List of Data Modules

:::

:::

## Define the Structure

The first part of the structure to define is the entities.
@tbl-entities_pc lists the entities again, but adds attributes that the entities will need to capture the performance of the system, e.g., waiting time until the cube was cut.
It is assumed that all entities have the three attributes: ID, CurrentActivity, and CurrentStart.
These are omitted in the table to prevent repetition.

::: {#tbl-entities_pc .sm .borderless}

```{=latex}
{{< include tables/entity_table.tex >}}
```

List of Entities

:::

The next part of the structure is the transitions, which describe how entities move between activities and events.
@tbl-transitions_pc lists the transitions for making paper cars.
These transitions are prefixed by entity of the behavioural pathway they come from.
Complete the transitions for the Scissors pathway.

::: {.content-visible unless-profile="answers"}

::: {#tbl-transitions_pc tbl-pos="H" .sm .column-page-right .borderless}

:::{.longtable}

{{< include tables/transition_table.tex >}}

:::

List of Transitions

:::

:::


::: {.content-visible when-profile="answers"}

::: {#tbl-transitions_pc tbl-pos="H" .sm .column-page-right .borderless}

:::{.longtable}

{{< include tables/transition_table_ans.tex >}}

:::

List of Transitions

:::

:::

@tbl-activities_pc lists the activities from the behavioural pathway diagrams along with the state changes for the start and end event of each activity.
Complete the activities for:

- Car Wait for Tape Car
- Tape Car
- Person Wait for Task (*Hint* look at Scissors Wait for Task)

::: {.content-visible unless-profile="answers"}

::: {#tbl-activities_pc .sm .column-page-right .borderless}

:::{.longtable}

{{< include tables/activity_table.tex >}}

:::

Activities

:::

:::

::: {.content-visible when-profile="answers"}

::: {#tbl-activities_pc .sm .column-page .borderless}

:::{.longtable}

{{< include tables/activity_table_ans.tex >}}

:::

Activities

:::

:::

@tbl-events_pc lists the events to start and finish the simulation along with the events from the behavioural pathway diagrams along with the state changes for each event.
Complete the activities for:

- Tape Pieces Created
- Person Created

::: {.content-visible unless-profile="answers"}

::: {#tbl-events_pc .sm .column-page .borderless}

:::{.longtable}

{{< include tables/event_table.tex >}}

:::

Events

:::

:::



::: {.content-visible when-profile="answers"}

::: {#tbl-events_pc .sm .column-page .borderless}

:::{.longtable}

{{< include tables/event_table_ans.tex >}}

:::

Events

:::

:::

## Define the Logic

The last part of the structure to define is the logic.
You need to define the logic for each of the triggers (the red squares in the behavioural paths, and TRIGGER statements in the state changes).
Tables XXX show the logic for some of the triggers.
Complete the logic for:
- On Tape Wait for Cut.Start
- On Cube Wait for Fold.Start
- the last condition of On Person Wait for Task.Start

::: {#tbl-start_pencil_wait_trace .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_pencil_wait_trace.tex >}}
:::

OnStartPencilWaitForTrace

:::

::: {#tbl-start_scissors_wait_task .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_scissors_wait_task.tex >}}
:::

OnStartScissorsWaitForTask

:::

::: {#tbl-start_tape_wait_cut .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_tape_wait_cut.tex >}}
:::

OnStartTapeWaitForCut

:::

::: {#tbl-start_tape_pieces_wait_tape .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_tape_pieces_wait_tape.tex >}}
:::

OnStartTapePiecesWaitForTape

:::

::: {#tbl-start_paper_wait_trace .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_paper_wait_trace.tex >}}
:::

OnStartPaperWaitForTrace

:::

::: {#tbl-start_paper_wait_cut .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_paper_wait_cut.tex >}}
:::

OnStartPaperWaitForCut

:::

::: {#tbl-start_paper_wait_fold .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_paper_wait_fold.tex >}}
:::

OnStartPaperWaitForFold

:::

::: {#tbl-start_paper_wait_tape .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_paper_wait_tape.tex >}}
:::

OnStartPaperWaitForTape

:::

::: {#tbl-start_person_wait_task .sm .column-page-right .borderless}

:::{.longtable}
{{< include tables/Logic/start_person_wait_task.tex >}}
:::

OnStartPersonWaitForTask

:::